### ISSUE TITLE
canonical transcript?

### ISSUE THREAD

**Issue by guandailu** [casanova-lab/BPHunter#1]
How canonical transcripts shown below are prepared?

if canonical == 'no':
    filename_bphunter_ref = 'Data_BPHunter_'+genome+'_detection_all.bed'
elif canonical == 'yes':
    filename_bphunter_ref = 'Data_BPHunter_'+genome+'_detection_canonical.bed'

**Comment by zhangpeng1202** [comment]
Hi, FarmOmics,

You can download them here: https://hgidsoft.rockefeller.edu/BPHunter/standalone.html, and put them in the same folder with the BPHunter.py program.

I have mentioned it in the readme page: 
Due to the file size limit in GitHub, please download the [BPHunter reference datasets](http://hgidsoft.rockefeller.edu/BPHunter/standalone.html) and put them into your BPHunter folder.

Thanks for your interest!

Best,
Peng
